services:
  # Backend Service
  - type: web
    name: Saniya_Backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false # You will get this from Neon
      - key: SECRET_KEY
        generateValue: true

  # Frontend Service
  - type: static_site
    name: Saniya_Frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: Saniya_Backend
          property: host
