services:
  - type: web
    name: smart-science-chatbot
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot_db
          property: connectionString

databases:
  - name: chatbot_db
    plan: free
